### ISSUE TITLE
Scrollbar at the bottom of the video

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastReferencePlayer#12] opened 2016-03-09 20:42 UTC
I've had some users report that they see a scrollbar at the bottom of the video. This seems to happen when the title of the video is particularly long. I've tested the solution by making a version with a shorter title and it works for them. I am unable to reproduce the issue on my end. I am using this CastReferencePlayer almost unmodified. 

This is what the user sees http://i.imgur.com/JsL8HUM.jpg

Anyone else had this issue?

**Comment by entertailion** [comment] 2016-03-09 20:49
We have had reports like this from other apps. We are investigating.

**Comment by entertailion** [comment] 2016-03-16 16:32
I've checked in a fix to handle the scrollbar issue. We are still investigating the cause.

**Closed by entertailion** 2016-03-16 16:32 UTC
